//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENT_Entity
    {
        public int ID_ENT { get; set; }
        public string NAME_ENT { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<bool> VALID { get; set; }
    }
}
