//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDatabaseEntities : DbContext
    {
        public TestDatabaseEntities()
            : base("name=TestDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComObjecTable> ComObjecTable { get; set; }
        public virtual DbSet<PLCTable> PLCTable { get; set; }
        public virtual DbSet<ResultTable> ResultTable { get; set; }
        public virtual DbSet<Table1> Table1 { get; set; }
        public virtual DbSet<USR_UserList> USR_UserList { get; set; }
        public virtual DbSet<ENT_Entity> ENT_Entity { get; set; }
        public virtual DbSet<STA_StateList> STA_StateList { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TRA_TranslationState> TRA_TranslationState { get; set; }
        public virtual DbSet<TRA_TranslationStateList> TRA_TranslationStateList { get; set; }
        public virtual DbSet<ENTITY> ENTITY { get; set; }
        public virtual DbSet<PRECHOD> PRECHOD { get; set; }
        public virtual DbSet<STAV> STAV { get; set; }
    }
}
