//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCTable
    {
        public string ID { get; set; }
        public int Status { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public int Slot { get; set; }
        public int Rack { get; set; }
        public string P_Created { get; set; }
        public string P_Modified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
