//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultTable
    {
        public long ID { get; set; }
        public System.DateTime PLCStamp { get; set; }
        public string IDComObject { get; set; }
        public int ResultData { get; set; }
    }
}
