//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_StateList
    {
        public int ID_STA { get; set; }
        public string Name_Entity { get; set; }
        public Nullable<int> State { get; set; }
        public string Purpous { get; set; }
        public Nullable<bool> L_START_STATE { get; set; }
        public Nullable<bool> L_END_STATE { get; set; }
        public Nullable<bool> L_VALID { get; set; }
        public string Comments { get; set; }
    }
}
