//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAV
    {
        public int ID { get; set; }
        public string NAZEV_ENTITY { get; set; }
        public int STAV1 { get; set; }
        public string VYZNAM { get; set; }
        public byte L_POC_STAV { get; set; }
        public byte L_KON_STAV { get; set; }
        public byte L_PLATNY { get; set; }
        public string POZNAMKA { get; set; }
    }
}
