//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComObjecTable
    {
        public string ID { get; set; }
        public string IDPLC { get; set; }
        public int Status { get; set; }
        public int ReadWrite { get; set; }
        public int AreaMemory { get; set; }
        public int Period { get; set; }
        public string P_Created { get; set; }
        public string P_Modified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public int StartOffSet { get; set; }
        public int WorldLen { get; set; }
        public int DBnumber { get; set; }
    }
}
