//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public Nullable<int> Value { get; set; }
        public int ID { get; set; }
        public string ComDevice { get; set; }
    }
}
