// <auto-generated />
namespace MES_2.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _170404 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_170404));
        
        string IMigrationMetadata.Id
        {
            get { return "201704161523216_170404"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
