//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_2.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_UserList
    {
        public int ID_USR { get; set; }
        public int ID_STA { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string Title_before { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Title_after { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> P_Created { get; set; }
        public Nullable<int> P_Modified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public string PASSWORD_reset_token { get; set; }
        public Nullable<System.DateTime> PASSWORD_reset_sent { get; set; }
        public Nullable<int> Count_SignIN { get; set; }
        public Nullable<System.DateTime> Current_SignIN { get; set; }
        public Nullable<System.DateTime> Last_SignIN { get; set; }
        public string Current_SignIN_IP { get; set; }
        public string Last_SignIN_IP { get; set; }
    }
}
